### ISSUE TITLE
It shows an alert periodically from v4.0. 

### ISSUE THREAD

**Issue by connor-15** [thang-nm/Tower-cracked#3]
![Screen Shot](https://user-images.githubusercontent.com/16561299/75019943-62851c00-5457-11ea-8245-7cdfa607f945.png)

**Comment by thang-nm** [comment]
Thank you, i will investigate!

**Comment by thang-nm** [comment]
Hi @connor-15, I've just fixed and uploaded new version 4.1. Please download latest version at [Releases page](https://github.com/thang-nm/Tower-cracked/releases).
It happens when app checks for updates.
But I think you shouldn't turn on the auto-update. Because if you update it, cracking will be gone!

**Comment by connor-15** [comment]
Thank you
